### ISSUE TITLE
Failing unit test in 2.0.2

### ISSUE THREAD

**Issue by danieldk** [tsproisl/SoMaJo#10]
First of all, thanks for the great tokenizer! I just downloaded SoMaJo 2.0.2, but the unit tests seem to fail:

```
======================================================================
FAIL: test_xml_boundaries_01 (somajo.test.test_sentence_splitter.TestXMLBoundaries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/somajo/test/test_sentence_splitter.py", line 125, in test_xml_boundaries_01
    self._equal_xml("<foo>Foo bar. Foo bar.</foo>", ["<foo> <s> Foo bar . </s>", "<s> Foo bar . </s> </foo>"])
  File "/build/source/somajo/test/test_sentence_splitter.py", line 27, in _equal_xml
    self.assertEqual(sentences, tokenized_sentences)
AssertionError: Lists differ: ['<foo> Foo bar .', 'Foo bar . </foo>'] != ['<foo> <s> Foo bar . </s>', '<s> Foo bar . </s> </foo>']

First differing element 0:
'<foo> Foo bar .'
'<foo> <s> Foo bar . </s>'

- ['<foo> Foo bar .', 'Foo bar . </foo>']
+ ['<foo> <s> Foo bar . </s>', '<s> Foo bar . </s> </foo>']
?         ++++         +++++    ++++         +++++


======================================================================
FAIL: test_xml_boundaries_02 (somajo.test.test_sentence_splitter.TestXMLBoundaries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/somajo/test/test_sentence_splitter.py", line 128, in test_xml_boundaries_02
    self._equal_xml("<foo><i>Foo bar</i>. Foo <i>bar.</i></foo>", ["<foo> <s> <i> Foo bar </i> . </s>", "<s> Foo <i> bar . </i> </s> </foo>"])
  File "/build/source/somajo/test/test_sentence_splitter.py", line 27, in _equal_xml
    self.assertEqual(sentences, tokenized_sentences)
AssertionError: Lists differ: ['<foo> <i> Foo bar </i> .', 'Foo <i> bar . </i> </foo>'] != ['<foo> <s> <i> Foo bar </i> . </s>', '<s> Foo <i> bar . </i> </s> </foo>']

First differing element 0:
'<foo> <i> Foo bar </i> .'
'<foo> <s> <i> Foo bar </i> . </s>'

- ['<foo> <i> Foo bar </i> .', 'Foo <i> bar . </i> </foo>']
+ ['<foo> <s> <i> Foo bar </i> . </s>', '<s> Foo <i> bar . </i> </s> </foo>']
?         ++++                  +++++    ++++                  +++++


======================================================================
FAIL: test_xml_boundaries_03 (somajo.test.test_sentence_splitter.TestXMLBoundaries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/somajo/test/test_sentence_splitter.py", line 131, in test_xml_boundaries_03
    self._equal_xml("<foo><i>Foo bar.</i> Foo bar.</foo>", ["<foo> <i> <s> Foo bar . </s> </i>", "<s> Foo bar . </s> </foo>"])
  File "/build/source/somajo/test/test_sentence_splitter.py", line 27, in _equal_xml
    self.assertEqual(sentences, tokenized_sentences)
AssertionError: Lists differ: ['<foo> <i> Foo bar . </i>', 'Foo bar . </foo>'] != ['<foo> <i> <s> Foo bar . </s> </i>', '<s> Foo bar . </s> </foo>']

First differing element 0:
'<foo> <i> Foo bar . </i>'
'<foo> <i> <s> Foo bar . </s> </i>'

- ['<foo> <i> Foo bar . </i>', 'Foo bar . </foo>']
+ ['<foo> <i> <s> Foo bar . </s> </i>', '<s> Foo bar . </s> </foo>']
?             ++++         +++++         ++++         +++++


======================================================================
FAIL: test_xml_boundaries_04 (somajo.test.test_sentence_splitter.TestXMLBoundaries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/source/somajo/test/test_sentence_splitter.py", line 134, in test_xml_boundaries_04
    self._equal_xml("<foo>Foo <i>bar. Foo</i> bar.</foo>", ["<foo> <s> Foo <i> bar . </i> </s>", "<s> <i> Foo </i> bar . </s> </foo>"])
  File "/build/source/somajo/test/test_sentence_splitter.py", line 27, in _equal_xml
    self.assertEqual(sentences, tokenized_sentences)
AssertionError: Lists differ: ['<foo> Foo <i> bar .', 'Foo </i> bar . </foo>'] != ['<foo> <s> Foo <i> bar . </i> </s>', '<s> <i> Foo </i> bar . </s> </foo>']

First differing element 0:
'<foo> Foo <i> bar .'
'<foo> <s> Foo <i> bar . </i> </s>'

- ['<foo> Foo <i> bar .', 'Foo </i> bar . </foo>']
+ ['<foo> <s> Foo <i> bar . </i> </s>', '<s> <i> Foo </i> bar . </s> </foo>']

----------------------------------------------------------------------
Ran 407 tests in 30.426s

FAILED (failures=4)
```

Any ideas?

**Comment by tsproisl** [comment]
Yes, currently these four tests fail. The reason is simply that they test something that hasn't been implemented, yet :wink:. In a future version, I would like to add an option to output sentence boundaries as XML tags which is tricky if the input is already XML and you want to have well-formed XML output. I've already created some tests, but the actual functionality is not there, yet.

**Comment by danieldk** [comment]
I see. I have [packaged](https://github.com/danieldk/nix-packages/blob/master/pkgs/python-modules/somajo/default.nix) SoMaJo for Nix/NixOS. The standard Nix tooling runs unit tests and builds will fail if any of the unit tests fail (which is a good thing ;)). Wouldn't be better to add a @skip decorator on those tests if they don't pass yet?

I guess I'll add a patch which disables these tests, since I don't want to disable tests altogether.

**Comment by tsproisl** [comment]
> Wouldn't be better to add a @skip decorator to those tests if they don't pass yet?

Good idea! I've just updated the tests and created a new release.

**Comment by danieldk** [comment]
Thanks a lot!
